services:
  - type: web
    name: adl-ssip-engine
    env: docker
    plan: free
    region: singapore
    dockerfilePath: ./Dockerfile
    healthCheckPath: /healthz
    autoDeploy: true
    envVars:
      - key: PORT
        value: "10000"
      - key: INTERNAL_API_SECRET
        generateValue: true